title: Shalyam Project Updates
description: Daily and upcoming updates for the Shalyam project
baseurl: "" # Ensure this is blank if you're using a custom domain
url: "https://project.shalyam.com"
theme: jekyll-theme-minimal